global:
  scrape_interval: 10s
 
scrape_configs:
  - job_name: 'prometheus_master'
    scrape_interval: 5s
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'node_exporter_centos'
    scrape_interval: 5s
    static_configs:
#    - targets: ['192.168.121.11:9100']
    - targets: ['192.168.121.12:9100']
    - targets: ['192.168.121.13:9100']
    