---
# tasks file for ./roles/configure_nginx
    - name: NGINX | Create NGINX config files from template
      copy: src=./upstream.conf dest=/etc/nginx/conf.d/upstream.conf

    - name: NGINX | Create NGINX config files from template
      template: src=./nginx.conf.j2 dest=/etc/nginx/nginx.conf
      notify:
        - reload nginx
